# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('interval', models.CharField(choices=[('10', 'Daily'), ('20', 'Weekly')], default='10', max_length=2)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['interval', 'name'],
            },
        ),
        migrations.AddField(
            model_name='check',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Task'),
        ),
    ]
